version: '3.1'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}